


<div>
    <p>
        Hey! And thank you for checking out 1kv :) 
    </p>

   <p>
    This website is built using serverside rendered svelte that makes a request to my selfhosted CMS (content managment service).
   </p> 
   <p>
    All of the video and thumbnails are also hosted on my server, compressed and generated by a variety of scripts. 
   </p>
   <p>
    Additionally, I have a Jenkins pipeline implemented that will rebuild this site on any change in the CMS or in the source code repo.
   </p>
   
   <p>
    Having grown disillusioned with the massive payloads generated by React, and with Single Page Applications as a philosophy, I wanted to write an 
    app that returns us to more lightweight era. 
   </p>
</div>


<style>
    div {
        padding-left: 100px;
        padding-top: 100px;
    }

    @media screen and (max-width: 600px) {
        div {
            margin: 5px;
            padding: 5px;
        }
    }
</style>